server:
    port: ${SERVER_PORT:8083}
spring:
  application:
    name: wasel-ride
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/wasel_ride_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: ${JPA_SHOW_SQL:false}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      ride-requested: ${RIDE_REQUESTED_TOPIC:ride.requested}
      ride-matched: ${RIDE_MATCHED_TOPIC:ride.matched}
    topic:
      partitions: ${KAFKA_TOPIC_PARTITIONS:3}
      replicas: ${KAFKA_TOPIC_REPLICAS:1}
